# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'SearchView', :path => "../" #退到上一层文件夹，找.podspec文件

end
